return {}
-- return {
--   "folke/noice.nvim",
--   event = "VeryLazy",
--   opts = {
--   },
--   dependencies = {
--     "MunifTanjim/nui.nvim",
--     "rcarriga/nvim-notify",
--   },
--   config = function()
--     require("notify").setup({
--       stages = "slide", 
--       background_colour = "#000000",
--     })
--
--     require("noice").setup({
--       routes = {
--         {
--           filter = { event = "msg_show" },
--           view = "notify",
--         },
--       },
--     })
--
--     vim.notify = require("notify")
--   end,
-- }
