#set -g default-terminal "tmux-256color"
set -g default-terminal "xterm-256color"
#set -ga terminal-overrides ",*256col*:Tc"
set -ga terminal-overrides ",xterm-256color:Tc"

# Refresh status line every 5 seconds
set -g status-interval 5

# Length of tmux status line
set -g status-left-length 30
set -g status-right-length 150

# colors
set-option -g status-style bg=black,fg=white
set-option -g status-left "\
#[fg=colour255, bg=colour23]#{?client_prefix,#[bg=colour167],} #S \
#[fg=colour255, bg=colour235]#{?client_prefix,#[fg=colour167],} #{?window_zoomed_flag, 🔍,}"

set-window-option -g window-status-current-format "\
#[fg=colour235, bg=colour75] #I*\
#[fg=colour235, bg=colour75, bold] #W "

set-window-option -g window-status-format "\
#[fg=colour255,bg=colour235] #I\
#[fg=colour255, bg=colour235] #W "
